# How to create list

In [6]:
import numpy as np
arrylist=np.array([[1,2,3],[4,5,6],[7,8,9]])

arrylist

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arrylist.dtype

dtype('int32')

In [8]:
arrylist.shape

(3, 3)

In [9]:
arrylist.size

9

In [12]:
Zeros=np.zeros((2,5))

In [13]:
Zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
Zeros.dtype

dtype('float64')

In [15]:
Zeros.shape

(2, 5)

In [16]:
Zeros.size

10

In [19]:
rng =np.arange(15)

In [20]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
ispace=np.linspace(1,50,10)

In [28]:
ispace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [24]:
emp=np.empty((4,6))

In [25]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        9.34609111e-307, 1.33511018e-306, 1.33511969e-306],
       [6.23037996e-307, 6.23053954e-307, 9.34609790e-307,
        8.45593934e-307, 9.34600963e-307, 9.34603000e-307],
       [1.78018403e-306, 8.90106955e-307, 1.60218491e-306,
        1.78018403e-306, 1.69119330e-306, 6.23054633e-307],
       [1.24610927e-306, 1.05698817e-307, 1.11261638e-306,
        1.33511562e-306, 2.22522596e-306, 1.42410974e-306]])

In [ ]:
emp_like=np.emp_like(ispace)
emp_like

In [32]:
ide=np.identity((45))

In [33]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [34]:
ide.shape

(45, 45)

In [41]:
arr=np.arange(99)
print(arr)

print(arr.reshape(3,33))

print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56
  57 58 59 60 61 62 63 64 65]
 [66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89
  90 91 92 93 94 95 96 97 98]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]


(99,)

In [44]:
arr=arr.reshape(3,33)

arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [50]:
arr=arr.ravel()

In [51]:
arr.shape

(99,)

In [55]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [56]:
ar=np.array(x)

In [64]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
ar.sum(axis=0)

array([12, 15, 18])

In [60]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [62]:
sumarr=ar.sum(axis=0) + ar.sum(axis=1)
sumarr

array([18, 30, 42])

In [78]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [67]:
for iteam in ar.flat:
    print(iteam)
    

1
2
3
4
5
6
7
8
9


In [68]:
ar.ndim

2

In [69]:
ar.size

9

In [70]:
ar.nbytes

36

In [71]:
one=np.array([1,2,3,4,5,6,67,7])

In [72]:
one.argmax()

6

In [73]:
one.argmin()

0

In [74]:
one.argsort()

array([0, 1, 2, 3, 4, 5, 7, 6], dtype=int64)

In [79]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
ar2=np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [81]:
ar +ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  9,  9]])

In [82]:
 ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  8,  0]])

In [83]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [84]:
ar.sum()

45

In [85]:
ar.min()

1

In [86]:
ar.max()

9

In [87]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
np.where(ar>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [89]:
type(np.where(ar>5))

tuple

In [90]:
np.count_nonzero(ar)

9

In [91]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))